### ISSUE TITLE
Exception drawing ThreeDPlot

### ISSUE THREAD

**Issue by srstevenson** [ASIDataScience/scala-plotly-client#27]
When trying to create a surface plot following the [ThreeDPlot documentation](https://asidatascience.github.io/scala-plotly-client/latest/api/#co.theasi.plotly.ThreeDPlot), `draw` throws an `IllegalArgumentException` for me:

```
scala> val xs = Vector(-1.0, 0.0, 1.0)
xs: scala.collection.immutable.Vector[Double] = Vector(-1.0, 0.0, 1.0)

scala> val ys = Vector(0.0, 10.0)
ys: scala.collection.immutable.Vector[Double] = Vector(0.0, 10.0)

scala> val zs = Vector(Vector(1.0, 2.0, 1.0), Vector(5,0, 4.0, 5.0))
zs: scala.collection.immutable.Vector[scala.collection.immutable.Vector[Double]] = Vector(Vector(1.0, 2.0, 1.0), Vector(5.0, 0.0, 4.0, 5.0))

scala> val p = ThreeDPlot().withSurface(xs, ys, zs)
p: co.theasi.plotly.ThreeDPlot = ThreeDPlot(Vector(SurfaceXYZ(Vector(PDouble(-1.0), PDouble(0.0), PDouble(1.0)),Vector(PDouble(0.0), PDouble(10.0)),Vector(Vector(PDouble(1.0), PDouble(2.0), PDouble(1.0)), Vector(PDouble(5.0), PDouble(0.0), PDouble(4.0), PDouble(5.0))),SurfaceOptions(None,None,None,None))),ThreeDPlotOptions(AxisOptions(None,None,None,None,None,None,None,Font(None,None,None),Font(None,None,None),None,None,None,None),AxisOptions(None,None,None,None,None,None,None,Font(None,None,None),Font(None,None,None),None,None,None,None),AxisOptions(None,None,None,None,None,None,None,Font(None,None,None),Font(None,None,None),None,None,None,None)))

scala> draw(p, "foo")
java.lang.IllegalArgumentException: transpose requires all collections have the same size
  at scala.collection.generic.GenericTraversableTemplate$class.fail$1(GenericTraversableTemplate.scala:213)
  at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1$$anonfun$apply$1.apply(GenericTraversableTemplate.scala:220)
  at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1$$anonfun$apply$1.apply(GenericTraversableTemplate.scala:219)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1.apply(GenericTraversableTemplate.scala:219)
  at scala.collection.generic.GenericTraversableTemplate$$anonfun$transpose$1.apply(GenericTraversableTemplate.scala:217)
  at scala.collection.immutable.List.foreach(List.scala:381)
  at scala.collection.generic.GenericTraversableTemplate$class.transpose(GenericTraversableTemplate.scala:217)
  at scala.collection.AbstractTraversable.transpose(Traversable.scala:104)
  at co.theasi.plotly.writer.FigureWriter$.co$theasi$plotly$writer$FigureWriter$$seriesToColumns(FigureWriter.scala:99)
  at co.theasi.plotly.writer.FigureWriter$$anonfun$10.apply(FigureWriter.scala:73)
  at co.theasi.plotly.writer.FigureWriter$$anonfun$10.apply(FigureWriter.scala:72)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
  at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
  at co.theasi.plotly.writer.FigureWriter$.drawGrid(FigureWriter.scala:72)
  at co.theasi.plotly.writer.FigureWriter$.draw(FigureWriter.scala:19)
  at co.theasi.plotly.writer.ServerWriter$class.draw(ServerWriter.scala:26)
  at co.theasi.plotly.package$.draw(package.scala:34)
  at co.theasi.plotly.writer.ServerWriter$class.draw(ServerWriter.scala:44)
  at co.theasi.plotly.package$.draw(package.scala:34)
  at co.theasi.plotly.writer.ServerWriter$class.draw(ServerWriter.scala:34)
  at co.theasi.plotly.package$.draw(package.scala:34)
  ... 42 elided
```
This is using master at cbdd2a77bae5c908b722a47ad65c9a97412fcaa2.

**Comment by pbugnion** [comment]
This is strange. I can definitely reproduce this, but there's a test (the last test in `WriterSpec`) that tries to produce basically the same plot, with two y-values and three x-values. I've just pushed another commit that slightly expands the scope of that test. It all passes.

I'll look into this at the weekend.

**Comment by pbugnion** [comment]
Ah -- I found it. Your `zs` vector is badly formed because a decimal point became a comma:

```
val zs = Vector(Vector(1.0, 2.0, 1.0), Vector(         5,0,  <--here           4.0, 5.0))
```

We should definitely check this to avoid an obscure exception.

**Comment by srstevenson** [comment]
Aha, I don't know where that came from--good spot!
